# Generated by Django 4.2.11 on 2024-04-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
